#!/bin/bash
#Load the config file, $1 this is the config file
echo 'Loading configuration...'
source config/$1

#Initialize variables
echo 'Initializing...'
js=0
jsempty=0
css=0
cssempty=0

#Provides feedback stating the path about to be written to
echo "Compilation write path = $COMPILETO"

#Create the current time stamp, we will append this to the end of the file name.
now=$(date +"%Y%m%d%H%M%S")

#Feedback, begining file merge/combining files
echo 'Combining CSS and JavaScript files...'
for FILE in $FILES
do
	#Get the extension of the file to be minified
	ext=$(echo $FILE|awk -F . '{print $NF}')

	#Check if the file to be minified is a CSS file
	if [ "$ext" == "css" ]; then

		#Check if we've removed previous files
		if [ "$cssempty" == 0 ]; then

			#Remove previous files
			echo "Executing rm $COMPILETO$1*.css..."
			rm $COMPILETO$1-??????????????.css
			rm $COMPILETO$1-??????????????.min.css
			#Set flag so as to know previous files have been removed
			cssempty=1
		fi

		#Set flag so as to know we have CSS files to combine and minify
		css=1;

	else
		if [ "$jsempty" == 0 ]; then
			echo "Executing rm $COMPILETO$1*.js..."
			rm $COMPILETO$1-??????????????.js
			rm $COMPILETO$1-??????????????.min.js
			jsempty=1
		fi 
		js=1;
	fi
	#Set flag so as to know we have JS files to combine and minify
	cat $FILE >> "$COMPILETO$1-$now.$ext"
done


if [ "$css" == 1 ]; then
	echo 'Minifing CSS files...'
	java -jar yuicompressor/build/yuicompressor-2.4.7.jar "$COMPILETO$1-$now.css" -o "$COMPILETO$1-$now.min.css"
	echo "Wrote $COMPILETO$1-$now.min.css"
fi

if [ "$js" == 1 ]; then
	echo 'Minifing JavaScript files...'
	java -jar yuicompressor/build/yuicompressor-2.4.7.jar "$COMPILETO$1-$now.js" -o "$COMPILETO$1-$now.min.js"
	echo "Wrote $COMPILETO$1-$now.min.js"
fi

# A reference file is a file that contains nothing but the latest compilation time stamp

echo "$1-$now" > "$COMPILETO/$REF"

echo "Process complete :)";




