#!/bin/bash
# $1 this is the config file

echo 'Loading configuration...'

source config/$1

#tests=demo/source/css/*.css
#for t in $tests
#do
#  echo "Processing $t file..."  
#done

js=0
jsempty=0
css=0
cssempty=0

echo 'Initializing...'
# If the directory for this type does not exist, create it.
mkdir -p css
mkdir -p js

# Create the current time stamp, we will append this to the end of the file name.
now=$(date +"%Y%m%d%k%M%S")

echo 'Combining files...'
for FILE in $FILES
do
	# Get the extension of the file to be minified
	ext=$(echo $FILE|awk -F . '{print $NF}')

	# Check if the file to be minified is a CSS file
	if [ "$ext" == "css" ]; then

		# Check if we've removed previous files
		if [ "$cssempty" == 0 ]; then

			# Remove previous files
			rm css/main*.css
			# Set flag so as to know previous files have been removed
			cssempty=1
		fi

		# Set flag so as to know we have CSS files to combine and minify
		css=1;

	else
		if [ "$jsempty" == 0 ]; then
			rm js/main*.js
			jsempty=1
		fi 
		js=1;
	fi

	cat $FILE >> $ext/main$now.$ext
done


echo 'Minifing files...'
if [ "$css" == 1 ]; then
	java -jar yuicompressor/build/yuicompressor-2.4.7.jar "css/main$now.css" -o "css/main-$now.min.css"
fi

if [ "$js" == 1 ]; then
	java -jar yuicompressor/build/yuicompressor-2.4.7.jar "js/main$now.js" -o "js/main-$now.min.js"
fi

echo "Process complete :)";




