#!/bin/bash
COMPILETO="compiled/"
FILES="
	demo/source/css/a.css 
	demo/source/css/b.css
	demo/source/css/c.css
	demo/source/js/1.js
	demo/source/js/2.js
	demo/source/js/3.js
"

BASEPATH="some/path"


